if(NOT DEFINED INPUT)
    message(FATAL_ERROR "INPUT is required")
endif()
if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()
if(NOT DEFINED FUNCTION_NAME)
    message(FATAL_ERROR "FUNCTION_NAME is required")
endif()
if(NOT DEFINED ARRAY_NAME)
    message(FATAL_ERROR "ARRAY_NAME is required")
endif()

file(READ "${INPUT}" SPIRV_HEX HEX)
string(LENGTH "${SPIRV_HEX}" SPIRV_HEX_LENGTH)
math(EXPR SPIRV_HEX_REMAINDER "${SPIRV_HEX_LENGTH} % 8")
if(NOT SPIRV_HEX_REMAINDER EQUAL 0)
    message(FATAL_ERROR "SPIR-V input size is not a multiple of 32-bit words: ${INPUT}")
endif()

math(EXPR SPIRV_WORD_COUNT "${SPIRV_HEX_LENGTH} / 8")
set(CONTENT "#include \"vulkan_shaders.h\"\n\n")
string(APPEND CONTENT "#include <cstddef>\n")
string(APPEND CONTENT "#include <cstdint>\n\n")
string(APPEND CONTENT "namespace ldcompress::vulkan_detail {\n")
string(APPEND CONTENT "namespace {\n")
string(APPEND CONTENT "alignas(4) constexpr std::uint32_t ${ARRAY_NAME}[] = {\n")

if(SPIRV_WORD_COUNT GREATER 0)
    math(EXPR SPIRV_LAST_WORD "${SPIRV_WORD_COUNT} - 1")
    foreach(INDEX RANGE 0 ${SPIRV_LAST_WORD})
        math(EXPR OFFSET "${INDEX} * 8")
        string(SUBSTRING "${SPIRV_HEX}" ${OFFSET} 2 BYTE0)
        math(EXPR OFFSET "${OFFSET} + 2")
        string(SUBSTRING "${SPIRV_HEX}" ${OFFSET} 2 BYTE1)
        math(EXPR OFFSET "${OFFSET} + 2")
        string(SUBSTRING "${SPIRV_HEX}" ${OFFSET} 2 BYTE2)
        math(EXPR OFFSET "${OFFSET} + 2")
        string(SUBSTRING "${SPIRV_HEX}" ${OFFSET} 2 BYTE3)
        string(APPEND CONTENT "    0x${BYTE3}${BYTE2}${BYTE1}${BYTE0}U,\n")
    endforeach()
endif()

string(APPEND CONTENT "};\n")
string(APPEND CONTENT "}  // namespace\n\n")
string(APPEND CONTENT "VulkanShaderBytes ${FUNCTION_NAME}()\n")
string(APPEND CONTENT "{\n")
string(APPEND CONTENT "    return VulkanShaderBytes { ${ARRAY_NAME}, sizeof(${ARRAY_NAME}) };\n")
string(APPEND CONTENT "}\n\n")
string(APPEND CONTENT "}  // namespace ldcompress::vulkan_detail\n")

file(WRITE "${OUTPUT}" "${CONTENT}")
